# @package _global_

defaults:
  - _self_
  - datamodule: mnist.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: mnist.yaml
  - logger: null
  - trainer: gpu.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: "/home/nemodrive/workspace/ppsq/nerxploration/logs/train/runs/2022-11-13_14-49-03/checkpoints/epoch_007.ckpt"
